import { ALL_ROUTES, SEO_CONFIG } from "./config";
import type { ParsedPage, SeoIssue } from "./types";

// STEP 5 Task 1 — a small set of real, non-page routes the site serves
// (system-generated by Next.js — sitemap/robots/icon/OG-image), so
// broken-internal-link/canonical-target checks below don't misfire on
// links to these. Kept here (not config.ts's ALL_ROUTES) since these
// aren't "pages" in the audit sense — checkPage never crawls them.
const KNOWN_NON_PAGE_ROUTES = new Set(["/sitemap.xml", "/robots.txt", "/opengraph-image", "/icon.svg", "/favicon.ico"]);

function normalizePath(pathname: string): string {
  const stripped = pathname.split("?")[0].split("#")[0];
  return stripped.length > 1 && stripped.endsWith("/") ? stripped.slice(0, -1) : stripped || "/";
}

const KNOWN_PATHS = new Set([...ALL_ROUTES.map((r) => normalizePath(r.path)), ...KNOWN_NON_PAGE_ROUTES]);

/** All checks that only need a single parsed page — no cross-page context.
 * `auditedOrigin` is the origin actually being crawled (baseUrl passed to
 * runAudit), used for canonical-origin comparisons — not the static config
 * default, so auditing a different deployment doesn't misfire. */
export function checkPage(path: string, page: ParsedPage, auditedOrigin: string): SeoIssue[] {
  const issues: SeoIssue[] = [];
  const { title: titleRules, metaDescription: descRules, thinContentWordThreshold, minInternalLinksPerPage } = SEO_CONFIG.rules;

  if (page.fetchError) {
    issues.push({ type: "fetch-failed", severity: "critical", category: "technical", page: path, message: "Page could not be fetched.", evidence: page.fetchError });
    return issues; // nothing else is checkable without a response
  }

  if (page.httpStatus && page.httpStatus >= 400) {
    issues.push({ type: "http-error", severity: "critical", category: "technical", page: path, message: `Page returned HTTP ${page.httpStatus}.`, evidence: `status ${page.httpStatus}` });
  }

  // --- Indexability ---
  if (page.robotsMeta && /noindex/i.test(page.robotsMeta)) {
    issues.push({ type: "noindex-meta", severity: "critical", category: "indexability", page: path, message: "Page has a noindex robots meta tag, so it will not be indexed.", evidence: page.robotsMeta });
  }
  if (!page.canonical) {
    issues.push({ type: "missing-canonical", severity: "warning", category: "indexability", page: path, message: "Missing canonical tag." });
  } else {
    let sameOrigin = false;
    try {
      sameOrigin = new URL(page.canonical).origin === auditedOrigin;
    } catch {
      sameOrigin = false;
    }
    if (!sameOrigin) {
      issues.push({
        type: "canonical-origin-mismatch",
        severity: "critical",
        category: "indexability",
        page: path,
        message: "Canonical tag points to a different origin than the page it appears on.",
        evidence: `canonical=${page.canonical}, page origin=${auditedOrigin}`,
      });
    } else {
      // STEP 5 Task 1 — same-origin canonical: is the TARGET path itself
      // a real known route, and if so, is it actually this page (the
      // normal case) or a different one (a real conflict)?
      const canonicalPath = normalizePath(new URL(page.canonical).pathname);
      if (!KNOWN_PATHS.has(canonicalPath)) {
        issues.push({
          type: "canonical-target-invalid",
          severity: "critical",
          category: "indexability",
          page: path,
          message: "Canonical tag points to a path that isn't a real known route — search engines would be told the authoritative URL doesn't exist.",
          evidence: page.canonical,
        });
      } else if (canonicalPath !== normalizePath(path)) {
        issues.push({
          type: "canonical-points-elsewhere",
          severity: "warning",
          category: "indexability",
          page: path,
          message: `Canonical tag points to a different real page (${canonicalPath}) instead of itself — confirm this is intentional, not a conflict.`,
          evidence: page.canonical,
        });
      }
    }
  }

  // --- On-page ---
  if (!page.title) {
    issues.push({ type: "missing-title", severity: "critical", category: "on-page", page: path, message: "Missing <title>." });
  } else if (page.title.length < titleRules.minLength || page.title.length > titleRules.maxLength) {
    issues.push({
      type: "title-length",
      severity: "warning",
      category: "on-page",
      page: path,
      message: `Title length (${page.title.length}) is outside the recommended ${titleRules.minLength}-${titleRules.maxLength} characters.`,
      evidence: page.title,
    });
  }

  if (!page.metaDescription) {
    issues.push({ type: "missing-meta-description", severity: "warning", category: "on-page", page: path, message: "Missing meta description." });
  } else if (page.metaDescription.length < descRules.minLength || page.metaDescription.length > descRules.maxLength) {
    issues.push({
      type: "meta-description-length",
      severity: "opportunity",
      category: "on-page",
      page: path,
      message: `Meta description length (${page.metaDescription.length}) is outside the recommended ${descRules.minLength}-${descRules.maxLength} characters.`,
      evidence: page.metaDescription,
    });
  }

  if (page.h1s.length === 0) {
    issues.push({ type: "missing-h1", severity: "critical", category: "on-page", page: path, message: "No H1 heading found." });
  } else if (page.h1s.length > 1) {
    issues.push({ type: "multiple-h1", severity: "warning", category: "on-page", page: path, message: `Multiple H1 headings found (${page.h1s.length}); a page should have exactly one.`, evidence: page.h1s.join(" | ") });
  }

  if (page.h1s.length > 0 && page.h2s.length === 0 && page.wordCount > thinContentWordThreshold) {
    issues.push({ type: "no-subheadings", severity: "opportunity", category: "on-page", page: path, message: "Page has substantial content but no H2 subheadings to structure it." });
  }

  // --- Content ---
  if (page.wordCount < thinContentWordThreshold) {
    issues.push({
      type: "thin-content",
      severity: "warning",
      category: "content",
      page: path,
      message: `Thin content: only ~${page.wordCount} words (threshold ${thinContentWordThreshold}).`,
    });
  }

  const imagesWithoutAlt = page.images.filter((img) => !img.alt || img.alt.trim() === "");
  if (page.images.length > 0 && imagesWithoutAlt.length > 0) {
    issues.push({
      type: "missing-alt-text",
      severity: "warning",
      category: "content",
      page: path,
      message: `${imagesWithoutAlt.length} of ${page.images.length} images are missing descriptive alt text.`,
      evidence: imagesWithoutAlt.map((i) => i.src).join(", "),
    });
  }

  // --- Internal linking ---
  if (page.internalLinks.length < minInternalLinksPerPage) {
    issues.push({
      type: "low-internal-links",
      severity: "opportunity",
      category: "internal-linking",
      page: path,
      message: `Only ${page.internalLinks.length} internal link(s) found; consider linking to related service pages.`,
    });
  }

  // --- Structured data ---
  if (page.jsonLdTypes.length === 0) {
    issues.push({ type: "no-structured-data", severity: "opportunity", category: "structured-data", page: path, message: "No structured data (JSON-LD) found on this page." });
  }

  // --- STEP 5 Task 1 additions (all reuse already-parsed ParsedPage data
  // and static route config — no extra network request per page). ---

  // Open Graph metadata — affects how the page appears when shared on
  // social platforms, a real (if secondary) SEO/discoverability signal.
  const missingOg = [!page.ogTitle && "og:title", !page.ogDescription && "og:description", !page.ogUrl && "og:url"].filter(Boolean) as string[];
  if (missingOg.length > 0) {
    issues.push({ type: "missing-og-metadata", severity: "warning", category: "on-page", page: path, message: `Missing Open Graph metadata: ${missingOg.join(", ")}.`, evidence: missingOg.join(", ") });
  }

  // Heading hierarchy — an H3 with no H2 above it skips a level, which is
  // a real (if minor) accessibility/structure problem distinct from
  // "no subheadings at all" above.
  if (page.h3s.length > 0 && page.h2s.length === 0) {
    issues.push({ type: "heading-hierarchy-skip", severity: "opportunity", category: "on-page", page: path, message: "Page has H3 headings but no H2 — the heading hierarchy skips a level." });
  }

  // Broken internal links — every internal href should resolve to a real
  // known route (live page, configured redirect, or a system route like
  // /sitemap.xml). Checked against the site's own static route config,
  // not by fetching each link.
  const brokenLinks = page.internalLinks.filter((href) => !KNOWN_PATHS.has(normalizePath(href)));
  if (brokenLinks.length > 0) {
    issues.push({
      type: "broken-internal-link",
      severity: "warning",
      category: "technical",
      page: path,
      message: `${brokenLinks.length} internal link(s) point to a path that isn't a real known route on this site.`,
      evidence: brokenLinks.join(", "),
    });
  }

  // External links using insecure http:// — a minor best-practice signal,
  // detected from already-parsed link data (never fetched — STEP 5's
  // performance/scope rule against crawling external sites).
  const insecureExternal = page.externalLinks.filter((href) => href.startsWith("http://"));
  if (insecureExternal.length > 0) {
    issues.push({
      type: "insecure-external-link",
      severity: "opportunity",
      category: "technical",
      page: path,
      message: `${insecureExternal.length} external link(s) use insecure http:// instead of https://.`,
      evidence: insecureExternal.join(", "),
    });
  }

  return issues;
}

/** Cross-page checks that need the whole audited set: duplicate titles/
 * descriptions, and pages that exist but are never linked to internally.
 * Duplicates are reported once per affected page (not once per group) so
 * each becomes its own actionable, page-scoped issue/action-queue item. */
export function checkCrossPage(pages: { path: string; page: ParsedPage }[]): SeoIssue[] {
  const issues: SeoIssue[] = [];

  const byTitle = new Map<string, string[]>();
  const byDescription = new Map<string, string[]>();
  for (const { path, page } of pages) {
    if (page.title) byTitle.set(page.title, [...(byTitle.get(page.title) ?? []), path]);
    if (page.metaDescription) byDescription.set(page.metaDescription, [...(byDescription.get(page.metaDescription) ?? []), path]);
  }
  for (const [title, paths] of byTitle) {
    if (paths.length > 1) {
      for (const path of paths) {
        issues.push({
          type: "duplicate-title",
          severity: "warning",
          category: "on-page",
          page: path,
          message: `Title is duplicated across ${paths.length} pages.`,
          evidence: `"${title}" → ${paths.join(", ")}`,
        });
      }
    }
  }
  for (const [desc, paths] of byDescription) {
    if (paths.length > 1) {
      for (const path of paths) {
        issues.push({
          type: "duplicate-meta-description",
          severity: "warning",
          category: "on-page",
          page: path,
          message: `Meta description is duplicated across ${paths.length} pages.`,
          evidence: `"${desc.slice(0, 60)}…" → ${paths.join(", ")}`,
        });
      }
    }
  }

  const linkedTo = new Set<string>();
  for (const { page } of pages) {
    for (const link of page.internalLinks) linkedTo.add(link.split("?")[0].replace(/\/$/, "") || "/");
  }
  for (const { path } of pages) {
    const normalized = path.replace(/\/$/, "") || "/";
    if (normalized !== "/" && !linkedTo.has(normalized)) {
      issues.push({ type: "orphan-page", severity: "opportunity", category: "internal-linking", page: path, message: "Page is not linked to from any other audited page (orphan page)." });
    }
  }

  return issues;
}
