import { NextResponse } from "next/server";
import { consumeOAuthState } from "@/lib/seo-agent/gsc/oauthState";
import { exchangeCodeForTokens } from "@/lib/seo-agent/gsc/oauthClient";
import { saveTokens } from "@/lib/seo-agent/gsc/tokenStore";
import { getPropertyUrl } from "@/lib/seo-agent/gsc/config";
import { getConnectionStatus } from "@/lib/seo-agent/gsc/connection";
import { GscError, humanMessage } from "@/lib/seo-agent/gsc/errors";

// Google redirects the site owner's OWN browser here after they approve
// (or deny) access — this route can never receive a custom auth header,
// so its security comes entirely from the one-time, short-lived `state`
// value generated by /connect (STEP 3 Task 7's "validate OAuth
// callbacks"). Renders a plain HTML page since a real browser lands
// here directly; never includes a token, client secret, or raw Google
// error payload in that page.

function htmlResponse(title: string, message: string, ok: boolean): NextResponse {
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title></head>
<body style="font-family: system-ui, sans-serif; background:#000; color:#fff; display:flex; align-items:center; justify-content:center; min-height:100vh; margin:0;">
  <div style="max-width:480px; padding:2rem; text-align:center;">
    <h1 style="font-size:1.25rem;">${ok ? "✓ " : "✕ "}${title}</h1>
    <p style="color:#a1a1aa;">${message}</p>
  </div>
</body></html>`;
  return new NextResponse(html, { headers: { "Content-Type": "text/html; charset=utf-8" } });
}

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const error = searchParams.get("error");
  const code = searchParams.get("code");
  const state = searchParams.get("state");

  // Google itself reports denial via ?error=access_denied rather than
  // omitting `code` — check this first so the message is accurate.
  if (error) {
    return htmlResponse("Authorization denied", humanMessage("authorization-denied"), false);
  }

  const stateIsValid = await consumeOAuthState(state);
  if (!stateIsValid || !code) {
    return htmlResponse("Invalid authorization callback", humanMessage("invalid-callback"), false);
  }

  try {
    const tokens = await exchangeCodeForTokens(code);
    await saveTokens({
      accessToken: tokens.accessToken,
      refreshToken: tokens.refreshToken ?? "",
      expiresAt: tokens.expiresAt,
      scope: tokens.scope,
      propertyUrl: getPropertyUrl(),
    });
    return htmlResponse(
      "Search Console connected",
      `RJ Services is now authorized to read Search Console performance data for ${getPropertyUrl()}. You can close this tab.`,
      true
    );
  } catch (err) {
    // A duplicate/concurrent hit on this exact callback (e.g. a browser's
    // link-preload/prefetch firing alongside the real navigation, or a
    // double-click) can race with itself here: Google's authorization
    // code is single-use, so whichever request loses that race gets
    // rejected by Google's token endpoint even though the OTHER request —
    // for the same approved consent — already completed the connection.
    // Before showing an error, check whether that's what actually
    // happened: if a connection now exists, this was a benign race, not
    // a real failure, and the user genuinely is connected.
    if (err instanceof GscError && err.code === "invalid-callback") {
      const status = await getConnectionStatus();
      if (status.state === "connected") {
        return htmlResponse(
          "Search Console connected",
          `RJ Services is authorized to read Search Console performance data for ${getPropertyUrl()}. You can close this tab.`,
          true
        );
      }
    }
    const message = err instanceof GscError ? humanMessage(err.code) : humanMessage("unknown-error");
    return htmlResponse("Connection failed", message, false);
  }
}
